# ----
# Site

title: Strong[Typed]
url: "http://www.strongtyped.io"
baseurl:
google_analytics_key: UA-50926236-1
google_maps_javascript_api_key:
disqus_shortname: strongtyped
disqus_show_comment_count: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: 
author: 
  name: Strong[Typed]
  email:
  twitter: strongtyped
social:
  name: Frisco Template
  links:
    - https://github.com/CloudCannon/frisco-jekyll-template

# -----
# Build

permalink: /blog/:year/:month/:day/:title/

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"

jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  
# -----------
# CloudCannon

social_icons:
  - Twitter
  - Email
  - RSS

_comments:
  description: Text shown when sharing on social media
  blurb: Short bio or description of this person
